### ISSUE TITLE
Add labels to each issue

### ISSUE THREAD

**Issue by Security2431** [Security2431/2day-report#54]
TODO:
- [ ] Add new labels into github (frontend, expo)
- [ ] Assign every issue with entire label

Example:
This labels, I have had on my Saas project, feel free to use it
<img width="720" alt="Screenshot 2023-11-01 at 8 51 47 AM" src="https://github.com/Security2431/2day-report/assets/11134693/c179130b-088a-4968-a7af-b86a3c7fab50">

**Comment by duongyennhi** [comment]
Hello. Can I help you? May you assign it to me?

**Comment by Security2431** [comment]
Hey, @duongyennhi. Appreciate that 🙏 I've assigned you and added some clarifies to this issue. Can you do it?

**Comment by Security2431** [comment]
@duongyennhi 

Thank you for your participation! I appreciate your engagement and support. However, I would like to inform you that the issue you were referring to has been deprecated. I apologize for any inconvenience this may cause.

If you are still interested in contributing to our product, I encourage you to select another issue from our repository. You can choose any other open issue that aligns with your skills and interests. Once you have identified a suitable issue, you can fork the repository and start working on the contribution.
